name: Build and Publish Minecraft Fabric Mod

on:
  push:
    paths:
      - gradle.properties
      - src/main/resources/fabric.mod.json
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: ./build/libs/

    - name: Read gradle.properties
      id: read_properties
      run: |
        game_version=$(grep 'minecraft_version=' gradle.properties | cut -d'=' -f2)
        echo "game_version=$game_version" >> $GITHUB_ENV

    - name: Read fabric.mod.json
      id: read_fabric_mod_json
      run: |
        mod_name=$(jq -r '.name' src/main/resources/fabric.mod.json)
        version=$(jq -r '.version' src/main/resources/fabric.mod.json)
        echo "mod_name=$mod_name" >> $GITHUB_ENV
        echo "version=$version" >> $GITHUB_ENV

    - name: Publish to Modrinth
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}  # Ensure this secret is added to your GitHub repository
        VERSION: ${{ env.version }}
        MOD_NAME: ${{ env.mod_name }}
        GAME_VERSION: ${{ env.game_version }}
      run: |
        curl -X POST https://api.modrinth.com/v2/project/blockcountermod/version \
        -H "Authorization: Bearer $MODRINTH_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
          "name": "'"$MOD_NAME"' '"$VERSION"'",
          "version_number": "'"$VERSION"'",
          "dependencies": [],
          "game_versions": ["'"$GAME_VERSION"'"],
          "version_type": "release",
          "loaders": ["fabric"],
          "featured": true,
          "file_parts": ["./build/libs/'"$MOD_NAME"'-'"$VERSION"'.jar"],
          "changelog": "Release '"$VERSION"'",
          "release_channel": "stable"
        }' \
        -F "file=@./build/libs/${MOD_NAME}-${VERSION}.jar"
